# Makefile
# Copyright (C) 2024 John Jekel
# See the LICENSE file at the root of the project for licensing info.
#
# Makefile for the letc/core/alu testbench

####################################################################################################
# Testbench Configuration
####################################################################################################

TBENCH_TOP  := letc_core_alu_tb
RTL_SOURCES := $(RTL_ROOT)/letc/letc_pkg.sv $(RTL_ROOT)/letc/core/letc_core_pkg.sv $(RTL_ROOT)/letc/core/letc_core_alu.sv

####################################################################################################
# Add Targets!
####################################################################################################

include $(TBENCH_ROOT)/nonuvm.mk
