# Makefile
# Copyright (C) 2024 John Jekel
# See the LICENSE file at the root of the project for licensing info.
#
# Makefile for the example testbench
# This file is part of a set of example files used to demonstrate
# hardware/RTL/SystemVerilog concepts to those new to digital logic design.

####################################################################################################
# Testbench Configuration
####################################################################################################

TBENCH_TOP  := counter_tb
RTL_SOURCES := \
    $(RTL_ROOT)/common/counter/counter.sv \
    $(RTL_ROOT)/letc/letc_pkg.sv

####################################################################################################
# Add Targets!
####################################################################################################

include $(TBENCH_ROOT)/nonuvm.mk
