# Makefile
# Copyright (C) 2024 John Jekel
# See the LICENSE file at the root of the project for licensing info.
#
# Makefile for the letc/core/gen_imm testbench

####################################################################################################
# Testbench Configuration
####################################################################################################

TBENCH_TOP  := letc_core_stage_d_tb
RTL_SOURCES := $(RTL_ROOT)/letc/letc_pkg.sv $(RTL_ROOT)/letc/core/letc_core_pkg.sv $(RTL_ROOT)/letc/core/letc_core_branch_comparator.sv $(RTL_ROOT)/letc/core/letc_core_stage_d.sv

####################################################################################################
# Add Targets!
####################################################################################################

include $(TBENCH_ROOT)/nonuvm.mk
