# Makefile
# Copyright (C) 2024 John Jekel
# See the LICENSE file at the root of the project for licensing info.
#
# Makefile for the learning testbench

####################################################################################################
# Testbench Configuration
####################################################################################################

TBENCH_TOP  := learning_tb
RTL_SOURCES := $(RTL_ROOT)/learning.sv

####################################################################################################
# Add Targets!
####################################################################################################

include $(TBENCH_ROOT)/nonuvm.mk
