# Makefile
# Copyright (C) 2024 John Jekel
# See the LICENSE file at the root of the project for licensing info.
#
# Makefile for the common/fifo/devel testbench

####################################################################################################
# Testbench Configuration
####################################################################################################

TBENCH_TOP  := fifo_0r1w_tb
RTL_SOURCES := $(RTL_ROOT)/common/fifo/fifo_0r1w.sv

####################################################################################################
# Add Targets!
####################################################################################################

include $(TBENCH_ROOT)/nonuvm.mk
