name: LETC Lint

#Thanks https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master
on:
  push:
    branches: [ "**", "!legacy", "!old_main" ]
  pull_request:
    branches: [ "**", "!legacy", "!old_main" ]

jobs:
  svlint:
    strategy:
      fail-fast: false
      matrix:
        #We only support Linux
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v3

      - name: Cache svlint Installation
        id: cache-svlint
        uses: actions/cache@v3
        env:
          cache-name: cache-svlint-installation
        with:
          path: ~/.cargo
          key: ${{runner.os}}-build-${{env.cache-name}}

      - if: ${{ steps.cache-svlint.outputs.cache-hit != 'true' }}
        name: Install svlint Compile Dependencies
        run: sudo apt-get install cargo

      - if: ${{ steps.cache-svlint.outputs.cache-hit != 'true' }}
        name: Compile svlint
        run: cargo install svlint

      - name: Run svlint
        working-directory: ${{github.workspace}}
        run: |
          . "$HOME/.cargo/env"
          make svlint

  verible:
    strategy:
      fail-fast: false
      matrix:
        #We only support Linux
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Install Verible Dependencies
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get -y install --no-install-recommends git python3 python3-click python3-unidiff
      - name: Install Verible
        uses: chipsalliance/verible-actions-common/install-verible@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Verible Lint
        working-directory: ${{github.workspace}}
        run: |
          make verible
