name: LETC stubmss Regression

#Thanks https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master
on:
  push:
    branches: [ "**", "!legacy", "!old_main" ]
  pull_request:
    branches: [ "**", "!legacy", "!old_main" ]

jobs:
  stubmss_regression:
    strategy:
      fail-fast: false
      matrix:
        #We only support Linux
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Verilator
        run: sudo apt-get install -y verilator

      - name: Cache RISC-V Toolchain
        id: cache-riscv
        uses: actions/cache@v3
        env:
          cache-name: cache-riscv-toolchain
        with:
          path: ~/.riscv
          key: ${{runner.os}}-build-${{env.cache-name}}

      - if: ${{ steps.cache-riscv.outputs.cache-hit != 'true' }}
        name: Install RISC-V Toolchain Dependencies
        run: sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      # Go back to a release before they switched to shallow submodules because apparently sourceware becomes unhappy otherwise
      - if: ${{ steps.cache-riscv.outputs.cache-hit != 'true' }}
        name: Get RISC-V Toolchain Sources
        working-directory: ${{github.workspace}}
        run: git clone --depth 1 --branch 2024.10.28 https://github.com/riscv/riscv-gnu-toolchain

      - if: ${{ steps.cache-riscv.outputs.cache-hit != 'true' }}
        name: Configure RISC-V Toolchain Sources
        working-directory: ${{github.workspace}}/riscv-gnu-toolchain/
        run: ./configure --prefix=$HOME/.riscv --with-arch=rv32i --with-abi=ilp32
        #run: ./configure --prefix=$HOME/.riscv --with-arch=rv32ima --with-abi=ilp32#TODO switch to this once these instructions are supported

      - if: ${{ steps.cache-riscv.outputs.cache-hit != 'true' }}
        name: Compile RISC-V Toolchain
        working-directory: ${{github.workspace}}/riscv-gnu-toolchain/
        timeout-minutes: 120
        run: make -j4

      - name: Add Toolchain Directory To Path
        run: echo "$HOME/.riscv/bin" >> $GITHUB_PATH

      - name: Compile IRVE
        working-directory: ${{github.workspace}}
        run: make -j4 irve

      - name: Compile RVSW
        working-directory: ${{github.workspace}}
        run: make -j4 software

      - name: Compile stubmss testbench
        working-directory: ${{github.workspace}}
        run: make stubmss_build

      - name: Run stubmss regression
        working-directory: ${{github.workspace}}
        run: infra/scripts/stubmss_regression.sh

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
